version: '3.7'

services:

  star_wars_movies:
    container_name: star_wars_movies
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/star-wars'
      - '/star-wars/node_modules'
    ports:
      - 5555:80
    environment:
      - CHOKIDAR_USEPOLLING=true